<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'id' => Str::uuid(),
                'name' => 'Victor',
                'apellido_paterno' => 'Valdez',
                'apellido_materno' => 'Huanacuni',
                'dni' => '73638061',
                'sexo' => 'M',
                'celular' => '956789431',
                'fecha_nacimiento' => '1992-11-11',
                'email' => 'superadmin@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'María',
                'apellido_paterno' => 'García',
                'apellido_materno' => 'Flores',
                'dni' => '73638062',
                'sexo' => 'F',
                'celular' => '956789432',
                'fecha_nacimiento' => '1985-05-21',
                'email' => 'admin@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Carlos',
                'apellido_paterno' => 'Torres',
                'apellido_materno' => 'Lopez',
                'dni' => '73638063',
                'sexo' => 'M',
                'celular' => '956789433',
                'fecha_nacimiento' => '1988-07-19',
                'email' => 'director@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Ana',
                'apellido_paterno' => 'Rojas',
                'apellido_materno' => 'Martínez',
                'dni' => '73638064',
                'sexo' => 'F',
                'celular' => '956789434',
                'fecha_nacimiento' => '1990-09-15',
                'email' => 'coordinador@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Luis',
                'apellido_paterno' => 'Castillo',
                'apellido_materno' => 'Ramírez',
                'dni' => '73638065',
                'sexo' => 'M',
                'celular' => '956789435',
                'fecha_nacimiento' => '1995-03-10',
                'email' => 'secretaria@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Sofía',
                'apellido_paterno' => 'Vega',
                'apellido_materno' => 'Pérez',
                'dni' => '73638066',
                'sexo' => 'F',
                'celular' => '956789436',
                'fecha_nacimiento' => '1996-12-01',
                'email' => 'docente1@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Javier',
                'apellido_paterno' => 'Mendoza',
                'apellido_materno' => 'Salazar',
                'dni' => '73638067',
                'sexo' => 'M',
                'celular' => '956789437',
                'fecha_nacimiento' => '1997-08-05',
                'email' => 'docente2@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Lucía',
                'apellido_paterno' => 'Reyes',
                'apellido_materno' => 'Campos',
                'dni' => '73638068',
                'sexo' => 'F',
                'celular' => '956789438',
                'fecha_nacimiento' => '1998-10-30',
                'email' => 'docente3@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Miguel',
                'apellido_paterno' => 'Paredes',
                'apellido_materno' => 'Quispe',
                'dni' => '73638069',
                'sexo' => 'M',
                'celular' => '956789439',
                'fecha_nacimiento' => '1999-02-14',
                'email' => 'docente4@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Elena',
                'apellido_paterno' => 'Morales',
                'apellido_materno' => 'Ticona',
                'dni' => '73638070',
                'sexo' => 'F',
                'celular' => '956789440',
                'fecha_nacimiento' => '2000-06-22',
                'email' => 'alumno1@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Carlos',
                'apellido_paterno' => 'Quispe',
                'apellido_materno' => 'Mamani',
                'dni' => '73638071',
                'sexo' => 'M',
                'celular' => '956789441',
                'fecha_nacimiento' => '2001-01-10',
                'email' => 'alumno2@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Lucía',
                'apellido_paterno' => 'Flores',
                'apellido_materno' => 'Cruz',
                'dni' => '73638072',
                'sexo' => 'F',
                'celular' => '956789442',
                'fecha_nacimiento' => '2002-03-15',
                'email' => 'alumno3@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'José',
                'apellido_paterno' => 'Condori',
                'apellido_materno' => 'Huanca',
                'dni' => '73638073',
                'sexo' => 'M',
                'celular' => '956789443',
                'fecha_nacimiento' => '2000-07-05',
                'email' => 'alumno4@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'María',
                'apellido_paterno' => 'Apaza',
                'apellido_materno' => 'Choque',
                'dni' => '73638074',
                'sexo' => 'F',
                'celular' => '956789444',
                'fecha_nacimiento' => '2001-11-21',
                'email' => 'alumno5@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Pedro',
                'apellido_paterno' => 'Choque',
                'apellido_materno' => 'Calsina',
                'dni' => '73638075',
                'sexo' => 'M',
                'celular' => '956789445',
                'fecha_nacimiento' => '2002-05-30',
                'email' => 'alumno6@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Ana',
                'apellido_paterno' => 'Tito',
                'apellido_materno' => 'Mamani',
                'dni' => '73638076',
                'sexo' => 'F',
                'celular' => '956789446',
                'fecha_nacimiento' => '2000-09-14',
                'email' => 'alumno7@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Miguel',
                'apellido_paterno' => 'Cusi',
                'apellido_materno' => 'Condori',
                'dni' => '73638077',
                'sexo' => 'M',
                'celular' => '956789447',
                'fecha_nacimiento' => '2001-04-18',
                'email' => 'alumno8@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Carmen',
                'apellido_paterno' => 'Vilca',
                'apellido_materno' => 'Laura',
                'dni' => '73638078',
                'sexo' => 'F',
                'celular' => '956789448',
                'fecha_nacimiento' => '2002-08-09',
                'email' => 'alumno9@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Luis',
                'apellido_paterno' => 'Paredes',
                'apellido_materno' => 'Quispe',
                'dni' => '73638079',
                'sexo' => 'M',
                'celular' => '956789449',
                'fecha_nacimiento' => '2000-12-03',
                'email' => 'alumno10@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Gloria',
                'apellido_paterno' => 'Callata',
                'apellido_materno' => 'Mamami',
                'dni' => '73638080',
                'sexo' => 'F',
                'celular' => '956789450',
                'fecha_nacimiento' => '2001-06-27',
                'email' => 'alumno11@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Hugo',
                'apellido_paterno' => 'Sánchez',
                'apellido_materno' => 'Turpo',
                'dni' => '73638081',
                'sexo' => 'M',
                'celular' => '956789451',
                'fecha_nacimiento' => '2002-02-13',
                'email' => 'alumno12@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Rosa',
                'apellido_paterno' => 'Cahuana',
                'apellido_materno' => 'Calsina',
                'dni' => '73638082',
                'sexo' => 'F',
                'celular' => '956789452',
                'fecha_nacimiento' => '2000-10-19',
                'email' => 'alumno13@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Jorge',
                'apellido_paterno' => 'Turpo',
                'apellido_materno' => 'Apaza',
                'dni' => '73638083',
                'sexo' => 'M',
                'celular' => '956789453',
                'fecha_nacimiento' => '2001-03-24',
                'email' => 'alumno14@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Patricia',
                'apellido_paterno' => 'Choque',
                'apellido_materno' => 'Huanca',
                'dni' => '73638084',
                'sexo' => 'F',
                'celular' => '956789454',
                'fecha_nacimiento' => '2002-07-08',
                'email' => 'alumno15@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Ricardo',
                'apellido_paterno' => 'Quispe',
                'apellido_materno' => 'Chambi',
                'dni' => '73638085',
                'sexo' => 'M',
                'celular' => '956789455',
                'fecha_nacimiento' => '2000-05-11',
                'email' => 'alumno16@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Verónica',
                'apellido_paterno' => 'Ticona',
                'apellido_materno' => 'Laura',
                'dni' => '73638086',
                'sexo' => 'F',
                'celular' => '956789456',
                'fecha_nacimiento' => '2001-09-02',
                'email' => 'alumno17@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Oscar',
                'apellido_paterno' => 'Calsina',
                'apellido_materno' => 'Sánchez',
                'dni' => '73638087',
                'sexo' => 'M',
                'celular' => '956789457',
                'fecha_nacimiento' => '2002-01-06',
                'email' => 'alumno18@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Sandra',
                'apellido_paterno' => 'Vilca',
                'apellido_materno' => 'Condori',
                'dni' => '73638088',
                'sexo' => 'F',
                'celular' => '956789458',
                'fecha_nacimiento' => '2000-04-17',
                'email' => 'alumno19@user.com',
                'password' => Hash::make('password'),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Eduardo',
                'apellido_paterno' => 'Mamani',
                'apellido_materno' => 'Choque',
                'dni' => '73638089',
                'sexo' => 'M',
                'celular' => '956789459',
                'fecha_nacimiento' => '2001-12-29',
                'email' => 'alumno20@user.com',
                'password' => Hash::make('password'),
            ],
        ];

        DB::table('users')->insert($users);
    }
}
